export const indexMenu = 
    [
        {
            name:'基本信息',
            index:"1",
            m:[
                 {
                     name:'供应商管理',
                     index:"/index/gys"
                 },
                 {
                     name:'客户管理',
                     index:"/WareHouse"
                 }
             ]
        },
        {
            name:'业务处理',
            index:"2",
            m:[
                 {
                     name:'入库',
                     index:"/index/WareHouse"
                 },
                 {
                     name:'出库',
                     index:"/WareHouse"
                 }
             ]
        },
    ]