export const indexMenu = 
    [
        {
            name:'基本信息',
            index:"1",
            m:[
                 {
                     name:'供应商信息',
                     index:"/index/gys"
                 },
                 {
                     name:'客户信息',
                     index:"/index/custom"
                 },
                 {
                    name:'商品信息',
                    index:"/index/ware"
                },
             ]
        },
        {
            name:'业务处理',
            index:"2",
            m:[
                 {
                     name:'入库',
                     index:"/index/WareHouse"
                 },
                 {
                     name:'出库',
                     index:"/WareHouse"
                 }
             ]
        },
    ]